name: 'Terraform'

on:
  push:
    branches:
      - ci_cd
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-west-2'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.25

      - name: Terraform Init
        run: |
        cd blogmatica/dev
        terraform init
        env $(aws s3 cp $(cat secrets_path.txt) - | cat | xargs) terraform plan
#
#      - name: Terraform Format
#        run: cd blogmatica/dev && terraform fmt -check

#      - name: Terraform Plan
#        run: cd blogmatica/dev && env $(aws s3 cp $(cat secrets_path.txt) - | cat | xargs) terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: cd blogmatica/dev && env $(aws s3 cp $(cat secrets_path.txt) - | cat | xargs) terraform apply -auto-approve